version: "3.8"

services:
  calendar-test:
    build:
      context: ../
      dockerfile: build/calendar_test/Dockerfile
    container_name: calendar-test
    hostname: calendar-test
    ports:
      - "8090:8090"
      - "8091:8091"
    restart: always
    networks:
      - calendar

networks:
  calendar: